set_property SRC_FILE_INFO {cfile:D:/Projects/prj/AMD/image_processing/image_processing.srcs/constrs_1/new/pin.xdc rfile:../../../image_processing.srcs/constrs_1/new/pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports TMDS_0_tmds_clk_p]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M21 [get_ports {TMDS_0_tmds_data_p[0]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L21 [get_ports {TMDS_0_tmds_data_p[1]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21 [get_ports {TMDS_0_tmds_data_p[2]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports tmds_oen_0]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list top_bd_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_bd_i/image_process_0_video_stream_tdata_o[0]} {top_bd_i/image_process_0_video_stream_tdata_o[1]} {top_bd_i/image_process_0_video_stream_tdata_o[2]} {top_bd_i/image_process_0_video_stream_tdata_o[3]} {top_bd_i/image_process_0_video_stream_tdata_o[4]} {top_bd_i/image_process_0_video_stream_tdata_o[5]} {top_bd_i/image_process_0_video_stream_tdata_o[6]} {top_bd_i/image_process_0_video_stream_tdata_o[7]} {top_bd_i/image_process_0_video_stream_tdata_o[8]} {top_bd_i/image_process_0_video_stream_tdata_o[9]} {top_bd_i/image_process_0_video_stream_tdata_o[10]} {top_bd_i/image_process_0_video_stream_tdata_o[11]} {top_bd_i/image_process_0_video_stream_tdata_o[12]} {top_bd_i/image_process_0_video_stream_tdata_o[13]} {top_bd_i/image_process_0_video_stream_tdata_o[14]} {top_bd_i/image_process_0_video_stream_tdata_o[15]} {top_bd_i/image_process_0_video_stream_tdata_o[16]} {top_bd_i/image_process_0_video_stream_tdata_o[17]} {top_bd_i/image_process_0_video_stream_tdata_o[18]} {top_bd_i/image_process_0_video_stream_tdata_o[19]} {top_bd_i/image_process_0_video_stream_tdata_o[20]} {top_bd_i/image_process_0_video_stream_tdata_o[21]} {top_bd_i/image_process_0_video_stream_tdata_o[22]} {top_bd_i/image_process_0_video_stream_tdata_o[23]}]]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[0]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[1]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[2]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[3]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[4]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[5]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[6]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[7]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[8]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[9]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[10]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[11]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[12]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[13]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[14]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[15]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[16]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[17]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[18]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[19]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[20]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[21]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[22]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[23]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[24]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[25]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[26]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[27]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[28]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[29]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[30]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[31]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[32]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[33]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[34]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[35]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[36]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[37]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[38]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[39]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[40]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[41]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[42]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[43]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[44]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[45]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[46]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[47]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[48]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[49]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[50]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[51]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[52]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[53]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[54]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[55]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[56]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[57]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[58]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[59]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[60]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[61]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[62]} {top_bd_i/axi_mem_intercon_M00_AXI_RDATA[63]}]]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[0]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[1]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[2]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[3]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[4]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[5]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[6]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[7]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[8]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[9]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[10]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[11]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[12]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[13]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[14]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[15]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[16]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[17]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[18]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[19]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[20]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[21]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[22]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[23]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[24]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[25]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[26]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[27]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[28]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[29]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[30]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[31]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[32]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[33]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[34]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[35]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[36]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[37]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[38]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[39]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[40]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[41]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[42]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[43]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[44]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[45]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[46]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[47]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[48]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[49]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[50]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[51]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[52]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[53]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[54]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[55]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[56]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[57]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[58]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[59]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[60]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[61]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[62]} {top_bd_i/axi_vdma_0_M_AXI_MM2S_RDATA[63]}]]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_1 ila
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/clk [get_nets [list top_bd_i/clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_1/probe0]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe0 [get_nets [list {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[0]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[1]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[2]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[3]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[4]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[5]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[6]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[7]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[8]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[9]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[10]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[11]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[12]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[13]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[14]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[15]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[16]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[17]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[18]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[19]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[20]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[21]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[22]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[23]}]]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe1 [get_nets [list top_bd_i/v_axi4s_vid_out_0_vid_io_out_ACTIVE_VIDEO]]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe2 [get_nets [list top_bd_i/v_axi4s_vid_out_0_vid_io_out_HSYNC]]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe3 [get_nets [list top_bd_i/v_axi4s_vid_out_0_vid_io_out_VSYNC]]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe4 [get_nets [list top_bd_i/v_axi4s_vid_out_0_vtg_ce]]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe5 [get_nets [list top_bd_i/v_tc_0_vtiming_out_ACTIVE_VIDEO]]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_1 probe
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_1/probe6 [get_nets [list top_bd_i/v_tc_0_vtiming_out_HSYNC]]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk]
