
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_0_data_n[0]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_0_data_n[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_0_data_n[2]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_0_data_p[0]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_0_data_p[1]}]
#set_property IOSTANDARD TMDS_33 [get_ports {TMDS_0_data_p[2]}]
#set_property PACKAGE_PIN M21 [get_ports {TMDS_0_data_p[0]}]
#set_property PACKAGE_PIN M22 [get_ports {TMDS_0_data_n[0]}]
#set_property PACKAGE_PIN L21 [get_ports {TMDS_0_data_p[1]}]
#set_property PACKAGE_PIN L22 [get_ports {TMDS_0_data_n[1]}]
#set_property PACKAGE_PIN J21 [get_ports {TMDS_0_data_p[2]}]
#set_property PACKAGE_PIN J22 [get_ports {TMDS_0_data_n[2]}]

#set_property IOSTANDARD TMDS_33 [get_ports TMDS_0_clk_n]
#set_property IOSTANDARD TMDS_33 [get_ports TMDS_0_clk_p]
#set_property PACKAGE_PIN N22 [get_ports TMDS_0_clk_p]
#set_property PACKAGE_PIN P22 [get_ports TMDS_0_clk_n]
#set_property PACKAGE_PIN M19 [get_ports clk]

set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[0]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[3]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[6]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[14]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[19]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[23]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[5]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[1]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[4]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[9]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[10]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[11]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[16]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[18]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[20]}]
set_property MARK_DEBUG true [get_nets top_bd_i/v_axi4s_vid_out_0_vid_io_out_HSYNC]
set_property MARK_DEBUG true [get_nets top_bd_i/v_axi4s_vid_out_0_vid_io_out_VSYNC]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[7]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[8]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[17]}]
set_property MARK_DEBUG true [get_nets top_bd_i/v_axi4s_vid_out_0_vid_io_out_ACTIVE_VIDEO]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[2]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[12]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[13]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[15]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[21]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[22]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[1]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[6]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[8]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[15]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[22]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[9]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[13]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[17]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[19]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[21]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[23]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[0]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[3]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[7]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[11]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[12]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[14]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[16]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[20]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[2]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[4]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[5]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[10]}]
set_property MARK_DEBUG true [get_nets {top_bd_i/image_process_0_video_stream_tdata_o[18]}]

set_property MARK_DEBUG false [get_nets {top_bd_i/rgb2dvi_0/U0/DataEncoders[0].DataSerializer/sDataOut}]
set_property MARK_DEBUG false [get_nets {top_bd_i/rgb2dvi_0/U0/DataEncoders[2].DataSerializer/sDataOut}]
set_property MARK_DEBUG false [get_nets {top_bd_i/rgb2dvi_0/U0/DataEncoders[1].DataSerializer/sDataOut}]

set_property PACKAGE_PIN N22 [get_ports TMDS_0_tmds_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_0_tmds_clk_p]
set_property PACKAGE_PIN M21 [get_ports {TMDS_0_tmds_data_p[0]}]
set_property PACKAGE_PIN L21 [get_ports {TMDS_0_tmds_data_p[1]}]
set_property PACKAGE_PIN J21 [get_ports {TMDS_0_tmds_data_p[2]}]
set_property MARK_DEBUG false [get_nets top_bd_i/clk_wiz_0_locked]
set_property IOSTANDARD LVCMOS33 [get_ports tmds_oen_0]

set_property MARK_DEBUG true [get_nets top_bd_i/v_axi4s_vid_out_0_vtg_ce]
set_property MARK_DEBUG true [get_nets top_bd_i/v_tc_0_vtiming_out_VSYNC]
set_property MARK_DEBUG true [get_nets top_bd_i/v_tc_0_vtiming_out_VBLANK]
set_property MARK_DEBUG true [get_nets top_bd_i/v_tc_0_vtiming_out_HSYNC]
set_property MARK_DEBUG true [get_nets top_bd_i/v_tc_0_vtiming_out_HBLANK]
set_property MARK_DEBUG true [get_nets top_bd_i/v_tc_0_vtiming_out_ACTIVE_VIDEO]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list top_bd_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {top_bd_i/image_process_0_video_stream_tdata_o[0]} {top_bd_i/image_process_0_video_stream_tdata_o[1]} {top_bd_i/image_process_0_video_stream_tdata_o[2]} {top_bd_i/image_process_0_video_stream_tdata_o[3]} {top_bd_i/image_process_0_video_stream_tdata_o[4]} {top_bd_i/image_process_0_video_stream_tdata_o[5]} {top_bd_i/image_process_0_video_stream_tdata_o[6]} {top_bd_i/image_process_0_video_stream_tdata_o[7]} {top_bd_i/image_process_0_video_stream_tdata_o[8]} {top_bd_i/image_process_0_video_stream_tdata_o[9]} {top_bd_i/image_process_0_video_stream_tdata_o[10]} {top_bd_i/image_process_0_video_stream_tdata_o[11]} {top_bd_i/image_process_0_video_stream_tdata_o[12]} {top_bd_i/image_process_0_video_stream_tdata_o[13]} {top_bd_i/image_process_0_video_stream_tdata_o[14]} {top_bd_i/image_process_0_video_stream_tdata_o[15]} {top_bd_i/image_process_0_video_stream_tdata_o[16]} {top_bd_i/image_process_0_video_stream_tdata_o[17]} {top_bd_i/image_process_0_video_stream_tdata_o[18]} {top_bd_i/image_process_0_video_stream_tdata_o[19]} {top_bd_i/image_process_0_video_stream_tdata_o[20]} {top_bd_i/image_process_0_video_stream_tdata_o[21]} {top_bd_i/image_process_0_video_stream_tdata_o[22]} {top_bd_i/image_process_0_video_stream_tdata_o[23]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list top_bd_i/clk_wiz_0/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 24 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[0]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[1]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[2]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[3]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[4]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[5]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[6]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[7]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[8]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[9]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[10]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[11]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[12]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[13]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[14]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[15]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[16]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[17]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[18]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[19]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[20]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[21]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[22]} {top_bd_i/v_axi4s_vid_out_0_vid_io_out_DATA[23]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list top_bd_i/v_axi4s_vid_out_0_vid_io_out_ACTIVE_VIDEO]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list top_bd_i/v_axi4s_vid_out_0_vid_io_out_HSYNC]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 1 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list top_bd_i/v_axi4s_vid_out_0_vid_io_out_VSYNC]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list top_bd_i/v_axi4s_vid_out_0_vtg_ce]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list top_bd_i/v_tc_0_vtiming_out_ACTIVE_VIDEO]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list top_bd_i/v_tc_0_vtiming_out_HBLANK]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list top_bd_i/v_tc_0_vtiming_out_HSYNC]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list top_bd_i/v_tc_0_vtiming_out_VBLANK]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list top_bd_i/v_tc_0_vtiming_out_VSYNC]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clk_out1]
