# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/prj/AMD/image_processing/image_processing.srcs/sources_1/bd/top_bd/ip/top_bd_v_axi4s_vid_out_0_0/top_bd_v_axi4s_vid_out_0_0.xci
# IP: The module: 'top_bd_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/prj/AMD/image_processing/image_processing.gen/sources_1/bd/top_bd/ip/top_bd_v_axi4s_vid_out_0_0/top_bd_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Projects/prj/AMD/image_processing/image_processing.gen/sources_1/bd/top_bd/ip/top_bd_v_axi4s_vid_out_0_0/top_bd_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Projects/prj/AMD/image_processing/image_processing.srcs/sources_1/bd/top_bd/ip/top_bd_v_axi4s_vid_out_0_0/top_bd_v_axi4s_vid_out_0_0.xci
# IP: The module: 'top_bd_v_axi4s_vid_out_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/prj/AMD/image_processing/image_processing.gen/sources_1/bd/top_bd/ip/top_bd_v_axi4s_vid_out_0_0/top_bd_v_axi4s_vid_out_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/Projects/prj/AMD/image_processing/image_processing.gen/sources_1/bd/top_bd/ip/top_bd_v_axi4s_vid_out_0_0/top_bd_v_axi4s_vid_out_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_v_axi4s_vid_out_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
